language: ruby
before_install:
  - gem update --system
  - gem update bundler
bundler_args: --binstubs=./bundler_stubs
before_script:
  - bundle exec rake db:setup
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec spec
services:
  - postgresql
addons:
  postgresql: "9.4"
cache: bundler
